[2024-06-05T16:26:42.263+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T16:26:42.297+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2023-04-30T15:00:00+00:00 [queued]>
[2024-06-05T16:26:42.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2023-04-30T15:00:00+00:00 [queued]>
[2024-06-05T16:26:42.327+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T16:26:42.351+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2023-04-30 15:00:00+00:00
[2024-06-05T16:26:42.379+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7086) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T16:26:42.380+0000] {standard_task_runner.py:63} INFO - Started process 7257 to run task
[2024-06-05T16:26:42.380+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2023-04-30T15:00:00+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpe8xy65yi']
[2024-06-05T16:26:42.381+0000] {standard_task_runner.py:91} INFO - Job 604: Subtask pipeline
[2024-06-05T16:26:42.437+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2023-04-30T15:00:00+00:00 [running]> on host ece5ff154bbf
[2024-06-05T16:26:42.573+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2023-04-30T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-30T15:00:00+00:00'
[2024-06-05T16:26:42.574+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T16:26:43.748+0000] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2024-06-05T16:27:03.280+0000] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7778, acc_std: 0.0048
[2024-06-05T16:27:14.601+0000] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2024-06-05T16:27:14.601+0000] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2024-06-05T16:27:18.335+0000] {pipeline.py:129} INFO - Model is saved as /home/***/***_hw/data/models/cars_pipe_202406051627.pkl
[2024-06-05T16:27:18.338+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-05T16:27:18.338+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T16:27:18.345+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2023-04-30T15:00:00+00:00, execution_date=20230430T150000, start_date=20240605T162642, end_date=20240605T162718
[2024-06-05T16:27:18.391+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T16:27:18.405+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-05T16:27:18.414+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-05T20:38:57.546+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T20:38:57.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2023-04-30T15:00:00+00:00 [queued]>
[2024-06-05T20:38:57.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2023-04-30T15:00:00+00:00 [queued]>
[2024-06-05T20:38:57.564+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-05T20:38:57.572+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): pipeline> on 2023-04-30 15:00:00+00:00
[2024-06-05T20:38:57.581+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=12124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T20:38:57.582+0000] {standard_task_runner.py:63} INFO - Started process 12247 to run task
[2024-06-05T20:38:57.582+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2023-04-30T15:00:00+00:00', '--job-id', '1926', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpuzeexzdi']
[2024-06-05T20:38:57.583+0000] {standard_task_runner.py:91} INFO - Job 1926: Subtask pipeline
[2024-06-05T20:38:57.610+0000] {task_command.py:426} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2023-04-30T15:00:00+00:00 [running]> on host d0ff8214a49e
[2024-06-05T20:38:57.664+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2023-04-30T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-30T15:00:00+00:00'
[2024-06-05T20:38:57.665+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T20:38:57.666+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T20:38:57.666+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 73, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/train/homework.csv'
[2024-06-05T20:38:57.673+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, run_id=scheduled__2023-04-30T15:00:00+00:00, execution_date=20230430T150000, start_date=20240605T203857, end_date=20240605T203857
[2024-06-05T20:38:57.683+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1926 for task pipeline ([Errno 2] No such file or directory: './data/train/homework.csv'; 12247)
[2024-06-05T20:38:57.715+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-05T20:38:57.729+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T20:38:57.731+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
